// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGI5j2Yi7N_PeW4PB0DE45h4Y2otc7T5o',
    appId: '1:17918757596:web:399c6d14e07be94f658219',
    messagingSenderId: '17918757596',
    projectId: 'portfolio-33dfd',
    authDomain: 'portfolio-33dfd.firebaseapp.com',
    databaseURL: 'https://portfolio-33dfd-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-33dfd.appspot.com',
    measurementId: 'G-VX7HLV2K0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2r1KpHOC6_-cB2acwPhWNnV8NJzHqCY8',
    appId: '1:17918757596:android:a58174847dbd465f658219',
    messagingSenderId: '17918757596',
    projectId: 'portfolio-33dfd',
    databaseURL: 'https://portfolio-33dfd-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-33dfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBXqachYt5Sul0W7xIrHmYJ3Cq9kfh0w',
    appId: '1:17918757596:ios:4e334cd5d2660e88658219',
    messagingSenderId: '17918757596',
    projectId: 'portfolio-33dfd',
    databaseURL: 'https://portfolio-33dfd-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-33dfd.appspot.com',
    iosBundleId: 'com.example.rawalSamaj',
  );
}
